[project]
name = "document-iq-ui-bff"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "kafka-python",
    "pydantic",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
