version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"   # ðŸ‘ˆ LOCAL clients use this
      - "9092:9092"     # ðŸ‘ˆ Docker clients use this
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "bash", "-c", "nc -z localhost 9092"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0
    container_name: documentiq-mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

    command: --default-authentication-plugin=mysql_native_password

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  aggregator:
    build:
      context: .
      dockerfile: components/aggregator/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DOCUMENT_IQ_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DOCUMENT_IQ_REDIS_HOST: redis
      DOCUMENT_IQ_REDIS_PORT: 6379
    command: python -m document_iq_platform_aggregator.main

  dlq-tooling:
    build:
      context: .
      dockerfile: ops/dlq-tooling/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DOCUMENT_IQ_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DOCUMENT_IQ_REDIS_HOST: redis
      DOCUMENT_IQ_REDIS_PORT: 6379
    command: python -m document_iq_dlq_tooling.monitor

  ui-bff:
    build:
      context: .
      dockerfile: gateways/ui-bff/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    environment:
      DOCUMENT_IQ_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  ingestion-worker:
    build:
      context: .
      dockerfile: components/ingestion-worker/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DOCUMENT_IQ_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DOCUMENT_IQ_REDIS_HOST: redis
      DOCUMENT_IQ_REDIS_PORT: 6379
    volumes:
      - ingestion-data:/srv/data
    restart: unless-stopped

  classification-worker:
    build:
      context: .
      dockerfile: components/classification-worker/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DOCUMENT_IQ_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DOCUMENT_IQ_REDIS_HOST: redis
      DOCUMENT_IQ_REDIS_PORT: 6379
    env_file:
    - .env

    restart: unless-stopped

  layout-worker:
    build:
      context: .
      dockerfile: components/layout-worker/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DOCUMENT_IQ_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DOCUMENT_IQ_REDIS_HOST: redis
      DOCUMENT_IQ_REDIS_PORT: 6379
    env_file:
      - .env
    volumes:
      - ingestion-data:/srv/data
    restart: unless-stopped

  ocr-worker:
    build:
      context: .
      dockerfile: components/ocr-worker/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DOCUMENT_IQ_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DOCUMENT_IQ_REDIS_HOST: redis
      DOCUMENT_IQ_REDIS_PORT: 6379
    env_file:
      - .env
    restart: unless-stopped

  rag-engine:
    build:
      context: .
      dockerfile: components/rag-engine/Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DOCUMENT_IQ_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DOCUMENT_IQ_REDIS_HOST: redis
      DOCUMENT_IQ_REDIS_PORT: 6379
      DOCUMENT_IQ_CHROMA_PERSIST_DIR: /srv/chroma_data
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - rag_chroma_data:/srv/chroma_data

  account-component:
    build:
      context: .
      dockerfile: components/account-component/Dockerfile
    environment:
      DOCUMENT_IQ_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DOCUMENT_IQ_REDIS_HOST: redis
      DOCUMENT_IQ_REDIS_PORT: 6379
      DOCUMENT_IQ_CHROMA_PERSIST_DIR: /srv/chroma_data
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      - mysql
      - kafka

  application-component:
    build:
      context: .
      dockerfile: components/application-component/Dockerfile
    environment:
      DOCUMENT_IQ_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DOCUMENT_IQ_REDIS_HOST: redis
      DOCUMENT_IQ_REDIS_PORT: 6379
      DOCUMENT_IQ_CHROMA_PERSIST_DIR: /srv/chroma_data
    env_file:
      - .env
    ports:
      - "8002:8002"
    depends_on:
      - mysql
      - kafka

volumes:
  ingestion-data:
  rag_chroma_data:
  mysql_data: